# Streamlit Authenticator Configuration

cookie:
  expiry_days: 30
  key: REPLACE_WITH_YOUR_SECRET_KEY # ğŸ” Use a long, secure random string here
  name: stream_auth_cookie

credentials:
  usernames:
    ali:  # ğŸ‘¤ Username
      email: alimuhammadshaker@gmail.com
      name: Ali Muhammad
      password: $2b$12$NqN.r9QYk4j8.61h.s1S4.3f0e.s9G3K4T2F.w0E9Y.2Y7G4.1N5F  # ğŸ”’ Hashed password for "test"

preauthorized:
  emails:
    - alimuhammadshaker@gmail.com
